### ISSUE TITLE
Client crash while seeding a field

### ISSUE THREAD

**Issue by BorikGor** [Cediner/ArdClient#28]
20210221.b7d13fbc
Windows 10 10.0 x64, 1.8.0_265 amd64
Intel (Intel(R) UHD Graphics 620) - 4.4.0 - Build 26.20.100.8141

java.lang.OutOfMemoryError: GC overhead limit exceeded
	at haven.sloth.script.pathfinding.GobHitmap$HitTile.<init>(GobHitmap.java:32)
	at haven.sloth.script.pathfinding.GobHitmap$HitTile.<init>(GobHitmap.java:30)
	at haven.sloth.script.pathfinding.GobHitmap.fillspace(GobHitmap.java:219)
	at haven.sloth.script.pathfinding.GobHitmap.fill(GobHitmap.java:257)
	at haven.sloth.script.pathfinding.GobHitmap.add(GobHitmap.java:131)
	at haven.Gob.move(Gob.java:845)
	at haven.OCache.move(OCache.java:263)
	at haven.OCache.move(OCache.java:271)
	at haven.OCache.receive(OCache.java:1003)
	at haven.Session$RWorker.getobjdata(Session.java:320)
	at haven.Session$RWorker.run(Session.java:489)

Happened, while planting Barley seeds.

**Comment by Cediner** [comment]
I'll leave it open and watch.
