### ISSUE TITLE
Crash after enabling the new Butcher bot

### ISSUE THREAD

**Issue by BorikGor** [Cediner/ArdClient#29]
**Describe the bug**
Near live pigs, butchering pigs' corpses, using the butcher knife. The Butcher bot was ran and failed.
Pigs' corpses were skinned and the "Skin" option was checked in the bot window.

**To Reproduce**
Happened only once, haven't reproduced it yet.
Dump below.

**Expected behavior**

**Desktop:**
Dell Latitude 5400, Intel Grafix card

**Additional context**
20210221.b7d13fbc
Windows 10 10.0 x64, 1.8.0_265 amd64
Intel (Intel(R) UHD Graphics 620) - 4.4.0 - Build 26.20.100.8141

java.lang.IllegalStateException: Multi threaded access requested by thread Thread[Thread-27,5,Haven client] but is not allowed for language(s) js.
	at com.oracle.truffle.polyglot.PolyglotContextImpl.throwDeniedThreadAccess(PolyglotContextImpl.java:602)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.checkAllThreadAccesses(PolyglotContextImpl.java:521)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.enterThreadChanged(PolyglotContextImpl.java:440)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.enter(PolyglotContextImpl.java:401)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.enterIfNeeded(PolyglotContextImpl.java:378)
	at com.oracle.truffle.polyglot.PolyglotContextImpl.eval(PolyglotContextImpl.java:748)
	at org.graalvm.polyglot.Context.eval(Context.java:335)
	at org.graalvm.polyglot.Context.eval(Context.java:361)
	at haven.purus.pbot.gui.PBotWindow$2$1.run(PBotWindow.java:70)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Cediner** [comment]
Parallel threads.
