### ISSUE TITLE
Selecting Character and then crash

### ISSUE THREAD

**Issue by PizzaMinks** [Cediner/ArdClient#30]
20210221.1cd1fc0d
Windows 10 10.0 x64, 1.8.0_261 amd64
NVIDIA Corporation (GeForce GTX 750 Ti/PCIe/SSE2) - 4.6.0 NVIDIA 460.79

java.lang.ArrayIndexOutOfBoundsException: 17
	at haven.Equipory.addchild(Equipory.java:178)
	at haven.UI.newwidget(UI.java:210)
	at haven.RemoteUI.run(RemoteUI.java:66)
	at haven.MainFrame.run(MainFrame.java:369)
	at java.lang.Thread.run(Unknown Source)

**Comment by Cediner** [comment]
redownload the client and follow the instructions from the archive (the error does not correspond to the current state of the client)
