### ISSUE TITLE
Latest client won't start

### ISSUE THREAD

**Issue by BorikGor** [Cediner/ArdClient#31]
**Describe the bug**
After an update, using "RunMe.bat" the client does not start.
When using the "Run_console.bat", the following is shown:
C:\H&H\Ard>java -Xss1024k -Xms512m -Xmx1024M -jar build/hafen.jar -U https://game.havenandhearth.com/hres/ game.havenandhearth.com
Base URL: https://game.havenandhearth.com/hres/
Weird version number on gfx/hud/chr/melee (4 > 3)Mar 01, 2021 11:29:04 PM haven.sloth.io.Storage create
SEVERE: failed to create dynamic storage jdbc:sqlite:static.sqlite
org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
        at org.sqlite.core.DB.newSQLException(DB.java:941)
        at org.sqlite.core.DB.newSQLException(DB.java:953)
        at org.sqlite.core.DB.execute(DB.java:854)
        at org.sqlite.core.CoreStatement.exec(CoreStatement.java:80)
        at org.sqlite.jdbc3.JDBC3Statement.execute(JDBC3Statement.java:53)
        at org.sqlite.SQLiteConfig.apply(SQLiteConfig.java:152)
        at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:65)
        at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:28)
        at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:21)
        at org.sqlite.JDBC.createConnection(JDBC.java:115)
        at org.sqlite.SQLiteDataSource.getConnection(SQLiteDataSource.java:410)
        at haven.sloth.io.Storage.mkcon(Storage.java:109)
        at haven.sloth.io.Storage.<init>(Storage.java:71)
        at haven.sloth.io.Storage.create(Storage.java:59)
        at haven.DefSettings.init(DefSettings.java:377)
        at haven.MainFrame.main2(MainFrame.java:445)
        at haven.MainFrame.access$100(MainFrame.java:54)
        at haven.MainFrame$7.run(MainFrame.java:489)
        at java.lang.Thread.run(Thread.java:748)

SImilar issue is seen with other users, on another machines.

**Comment by Cediner** [comment]
You somehow started the client incorrectly. Delete the static.sqlite file from the folder and try again.
