### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by SaintBalbal** [Cediner/ArdClient#39]
First crash report comes then the game opens.

20210326.171f800f
Windows 10 10.0 x64, 1.8.0_281 amd64
null

org.armedbear.lisp.IntegrityError
	at org.armedbear.lisp.Primitives$pf_error.execute(Primitives.java:1577)
	at org.armedbear.lisp.Primitive.execute(Primitive.java:113)
	at org.armedbear.lisp.Symbol.execute(Symbol.java:803)
	at org.armedbear.lisp.Lisp.error(Lisp.java:383)
	at org.armedbear.lisp.Stream.readToken(Stream.java:1199)
	at org.armedbear.lisp.Stream.processChar(Stream.java:595)
	at org.armedbear.lisp.Stream.readList(Stream.java:755)
	at org.armedbear.lisp.LispReader$3.execute(LispReader.java:88)
	at org.armedbear.lisp.Stream.processChar(Stream.java:588)
	at org.armedbear.lisp.Stream.readPreservingWhitespace(Stream.java:557)
	at org.armedbear.lisp.Stream.readPreservingWhitespace(Stream.java:566)
	at org.armedbear.lisp.Stream.read(Stream.java:501)
	at org.armedbear.lisp.Load.loadStream(Load.java:625)
	at org.armedbear.lisp.Load.loadFileFromStream(Load.java:597)
	at org.armedbear.lisp.Load.loadFileFromStream(Load.java:477)
	at org.armedbear.lisp.Load.loadSystemFile(Load.java:375)
	at org.armedbear.lisp.Interpreter.initializeLisp(Interpreter.java:172)
	at org.armedbear.lisp.Interpreter.createInstance(Interpreter.java:72)
	at haven.sloth.script.LispScript.<clinit>(LispScript.java:10)
	at java.lang.Thread.run(Unknown Source)

**Comment by Cediner** [comment]
i don't know
java 8 x64
redownload the client

**Comment by SaintBalbal** [comment]
its already java 8 x64 and I redownloaded client so many times

**Comment by SaintBalbal** [comment]
org.armedbear.lisp.IntegrityError
        at org.armedbear.lisp.Primitives$pf_error.execute(Primitives.java:1577)
        at org.armedbear.lisp.Primitive.execute(Primitive.java:113)
        at org.armedbear.lisp.Symbol.execute(Symbol.java:803)
        at org.armedbear.lisp.Lisp.error(Lisp.java:383)
        at org.armedbear.lisp.Stream.readToken(Stream.java:1199)
        at org.armedbear.lisp.Stream.processChar(Stream.java:595)
        at org.armedbear.lisp.Stream.readList(Stream.java:755)
        at org.armedbear.lisp.LispReader$3.execute(LispReader.java:88)
        at org.armedbear.lisp.Stream.processChar(Stream.java:588)
        at org.armedbear.lisp.Stream.readPreservingWhitespace(Stream.java:557)
        at org.armedbear.lisp.Stream.readPreservingWhitespace(Stream.java:566)
        at org.armedbear.lisp.Stream.read(Stream.java:501)
        at org.armedbear.lisp.Load.loadStream(Load.java:625)
        at org.armedbear.lisp.Load.loadFileFromStream(Load.java:597)
        at org.armedbear.lisp.Load.loadFileFromStream(Load.java:477)
        at org.armedbear.lisp.Load.loadSystemFile(Load.java:375)
        at org.armedbear.lisp.Interpreter.initializeLisp(Interpreter.java:172)
        at org.armedbear.lisp.Interpreter.createInstance(Interpreter.java:72)
        at haven.sloth.script.LispScript.<clinit>(LispScript.java:10)
        at java.base/java.lang.Thread.run(Thread.java:834)
ERROR placeholder called with arguments:
The symbol "%IN-PACKAGE" was not found in package SYS.
The symbol "%IN-PACKAGE" was not found in package SYS.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
DiscordBot getJDA: Invalid Token
javax.security.auth.login.LoginException: The provided token is invalid!
        at net.dv8tion.jda.core.entities.impl.JDAImpl.verifyToken(JDAImpl.java:276)
        at net.dv8tion.jda.core.entities.impl.JDAImpl.verifyToken(JDAImpl.java:214)
        at net.dv8tion.jda.core.entities.impl.JDAImpl.login(JDAImpl.java:161)
        at net.dv8tion.jda.core.JDABuilder.buildAsync(JDABuilder.java:608)
        at haven.automation.DiscordBot.getJda(DiscordBot.java:16)
        at haven.purus.pbot.PBotDiscord.setChannelByName(PBotDiscord.java:27)
        at haven.purus.pbot.PBotDiscord.initalize(PBotDiscord.java:36)
        at haven.MainFrame.main2(MainFrame.java:447)
        at haven.MainFrame.access$100(MainFrame.java:54)
        at haven.MainFrame$7.run(MainFrame.java:489)
        at java.base/java.lang.Thread.run(Thread.java:834)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jogamp.common.os.NativeLibrary$3 (file:/C:/CustomClientUnstable/build/gluegen-rt.jar) to method java.lang.ClassLoader.findLibrary(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.jogamp.common.os.NativeLibrary$3
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Disposal was interrupted:
java.lang.InterruptedException
        at java.base/java.lang.Object.wait(Native Method)
        at java.base/java.lang.Object.wait(Object.java:328)
        at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1361)
        at java.desktop/java.awt.Window.doDispose(Window.java:1227)
        at java.desktop/java.awt.Window.dispose(Window.java:1164)
        at haven.MainFrame.run(MainFrame.java:382)
        at java.base/java.lang.Thread.run(Thread.java:834)
        
        thats the cmd error

**Comment by se7enek** [comment]
```
java -version
```
?

**Comment by SaintBalbal** [comment]
It was version 8 but i changed it to 11
java version "11.0.10" 2021-01-19 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.10+8-LTS-162)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.10+8-LTS-162, mixed mode)
now its like this.
