### ISSUE TITLE
Getting Crash help to fix ...

### ISSUE THREAD

**Issue by Jeky223** [Cediner/ArdClient#46]
Client was working well until i started to get this issue,i can play but seems like everytime i try to see a batwings or use a cape it is just crash client ,same issue with smoked shed.Any help?

Java 1.8.0_291-b10
OS Windows 10 10.0 amd64
GPU NVIDIA Corporation (NVIDIA GeForce GTX 1050/PCIe/SSE2) - 4.6.0 NVIDIA 466.27
java.lang.RuntimeException: Delayed error in resource gfx/invobjs/batwings (v1), from forking source backed by HTTP res source (https://game.havenandhearth.com/hres/)
	at haven.Resource$Pool$Queued.get(Resource.java:507)
	at haven.Resource$Pool$Queued.get(Resource.java:472)
	at haven.Session$CachedRes$Ref.get(Session.java:143)
	at haven.Session$CachedRes$Ref.get(Session.java:136)
	at haven.GItem.spr(GItem.java:203)
	at haven.GItem.tick(GItem.java:232)
	at haven.Widget.tick(Widget.java:787)
	at haven.Widget.tick(Widget.java:787)
	at haven.Widget.tick(Widget.java:787)
	at haven.GameUI.tick(GameUI.java:1318)
	at haven.Widget.tick(Widget.java:787)
	at haven.UI.tick(UI.java:187)
	at haven.HavenPanel.run(HavenPanel.java:753)
	at java.lang.Thread.run(Unknown Source)
Caused by: haven.Resource$LoadException: Load error in resource gfx/invobjs/batwings(v1), from forking source backed by HTTP res source (https://game.havenandhearth.com/hres/)
	at haven.Resource$Pool.handle(Resource.java:569)
	at haven.Resource$Pool.access$1200(Resource.java:449)
	at haven.Resource$Pool$Loader.run(Resource.java:715)
	... 1 more
	Suppressed: haven.Resource$LoadException: Load error in resource gfx/invobjs/batwings(v1), from cache source backed by HashDirCache(https://game.havenandhearth.com/hres/)
		... 4 more
		Suppressed: haven.Resource$LoadException: Load error in resource gfx/invobjs/batwings(v1), from local res source (res-preload)
			... 4 more
			Suppressed: haven.Resource$LoadException: Load error in resource gfx/invobjs/batwings(v1), from local res source (res)
				... 4 more
			Caused by: java.io.FileNotFoundException: Could not find resource locally: /res/gfx/invobjs/batwings.res
				at haven.Resource$JarSource.get(Resource.java:355)
				at haven.Resource$Pool.handle(Resource.java:553)
				... 3 more
		Caused by: java.io.FileNotFoundException: Could not find resource locally: /res-preload/gfx/invobjs/batwings.res
			at haven.Resource$JarSource.get(Resource.java:355)
			at haven.Resource$Pool.handle(Resource.java:553)
			... 3 more
	Caused by: java.io.IOException: Ошибка в данных (CRC)
		at java.io.RandomAccessFile.read0(Native Method)
		at java.io.RandomAccessFile.read(Unknown Source)
		at java.io.RandomAccessFile.readByte(Unknown Source)
		at haven.HashDirCache.readhead(HashDirCache.java:117)
		at haven.HashDirCache.lookup(HashDirCache.java:241)
		at haven.HashDirCache.fetch(HashDirCache.java:336)
		at haven.Resource$CacheSource.get(Resource.java:306)
		at haven.Resource$Pool.handle(Resource.java:553)
		... 3 more
Caused by: java.io.IOException: Ошибка в данных (CRC)
	at java.io.RandomAccessFile.read0(Native Method)
	at java.io.RandomAccessFile.read(Unknown Source)
	at java.io.RandomAccessFile.readByte(Unknown Source)
	at haven.HashDirCache.readhead(HashDirCache.java:117)
	at haven.HashDirCache.lookup(HashDirCache.java:241)
	at haven.HashDirCache.store(HashDirCache.java:311)
	at haven.Resource$1Caching.fork(Resource.java:858)
	at haven.Resource$TeeSource.get(Resource.java:287)
	at haven.Resource$Pool.handle(Resource.java:553)
	... 3 more

**Comment by Cediner** [comment]
Во-первых: какого хуя в твоём логе нету версии клиента - что-то мне подсказывает, что ты используешь какую-то хуйню, а не клиент
Во-вторых: попробуй функцию Modification - Dev - Resource Cleaner в настройках

**Comment by Jeky223** [comment]
Скачал клиент как и было написано ,запускаю через runMe.bat.
не понимаю где тут версия но ту я ошибку я скопировал с папки errors
а вот ошибка сразу скопирована если это чем то поможет
Запускал функцию resourse cleaner как ты написал ,та же ошибка .



2021.05.02.d64ee32a
Windows 10 10.0 x64, 1.8.0_291 amd64
NVIDIA Corporation (NVIDIA GeForce GTX 1050/PCIe/SSE2) - 4.6.0 NVIDIA 466.27

java.lang.RuntimeException: Delayed error in resource gfx/invobjs/batwings (v1), from forking source backed by HTTP res source (https://game.havenandhearth.com/hres/)
	at haven.Resource$Pool$Queued.get(Resource.java:507)
	at haven.Resource$Pool$Queued.get(Resource.java:472)
	at haven.Session$CachedRes$Ref.get(Session.java:143)
	at haven.Session$CachedRes$Ref.get(Session.java:136)
	at haven.GItem.spr(GItem.java:203)
	at haven.GItem.tick(GItem.java:232)
	at haven.Widget.tick(Widget.java:787)
	at haven.Widget.tick(Widget.java:787)
	at haven.Widget.tick(Widget.java:787)
	at haven.Widget.tick(Widget.java:787)
	at haven.GameUI.tick(GameUI.java:1318)
	at haven.Widget.tick(Widget.java:787)
	at haven.UI.tick(UI.java:187)
	at haven.HavenPanel.run(HavenPanel.java:753)
	at java.lang.Thread.run(Unknown Source)
Caused by: haven.Resource$LoadException: Load error in resource gfx/invobjs/batwings(v1), from forking source backed by HTTP res source (https://game.havenandhearth.com/hres/)
	at haven.Resource$Pool.handle(Resource.java:569)
	at haven.Resource$Pool.access$1200(Resource.java:449)
	at haven.Resource$Pool$Loader.run(Resource.java:715)
	... 1 more
	Suppressed: haven.Resource$LoadException: Load error in resource gfx/invobjs/batwings(v1), from cache source backed by HashDirCache(https://game.havenandhearth.com/hres/)
		... 4 more
		Suppressed: haven.Resource$LoadException: Load error in resource gfx/invobjs/batwings(v1), from local res source (res-preload)
			... 4 more
			Suppressed: haven.Resource$LoadException: Load error in resource gfx/invobjs/batwings(v1), from local res source (res)
				... 4 more
			Caused by: java.io.FileNotFoundException: Could not find resource locally: /res/gfx/invobjs/batwings.res
				at haven.Resource$JarSource.get(Resource.java:355)
				at haven.Resource$Pool.handle(Resource.java:553)
				... 3 more
		Caused by: java.io.FileNotFoundException: Could not find resource locally: /res-preload/gfx/invobjs/batwings.res
			at haven.Resource$JarSource.get(Resource.java:355)
			at haven.Resource$Pool.handle(Resource.java:553)
			... 3 more
	Caused by: java.io.IOException: Ошибка в данных (CRC)
		at java.io.RandomAccessFile.read0(Native Method)
		at java.io.RandomAccessFile.read(Unknown Source)
		at java.io.RandomAccessFile.readByte(Unknown Source)
		at haven.HashDirCache.readhead(HashDirCache.java:117)
		at haven.HashDirCache.lookup(HashDirCache.java:241)
		at haven.HashDirCache.fetch(HashDirCache.java:336)
		at haven.Resource$CacheSource.get(Resource.java:306)
		at haven.Resource$Pool.handle(Resource.java:553)
		... 3 more
Caused by: java.io.IOException: Ошибка в данных (CRC)
	at java.io.RandomAccessFile.read0(Native Method)
	at java.io.RandomAccessFile.read(Unknown Source)
	at java.io.RandomAccessFile.readByte(Unknown Source)
	at haven.HashDirCache.readhead(HashDirCache.java:117)
	at haven.HashDirCache.lookup(HashDirCache.java:241)
	at haven.HashDirCache.store(HashDirCache.java:311)
	at haven.Resource$1Caching.fork(Resource.java:858)
	at haven.Resource$TeeSource.get(Resource.java:287)
	at haven.Resource$Pool.handle(Resource.java:553)
	... 3 more

**Comment by Cediner** [comment]
Могу предложить ещё глянуть папку '%appdata%/Haven and Hearth/data'
Возможно, почистить её.
Ошибка указывает на кривой ресурс или ошибку в чтении файла.

**Comment by Jeky223** [comment]
Помогло ,большое спасибо
