### ISSUE TITLE
Client crashes, after choosing a character

### ISSUE THREAD

**Issue by BorikGor** [Cediner/ArdClient#49]
**Describe the bug**
Latest updated client.
When I click the character button, the client crashes with the following error message:
2021.05.19.c602926c
Windows 10 10.0 x64, 1.8.0_121 amd64
Intel (Intel(R) UHD Graphics 630) - 4.4.0 - Build 23.20.16.4944

java.lang.NullPointerException
	at haven.sloth.gui.ForageHelperWnd.removed(ForageHelperWnd.java:188)
	at haven.UI.removeid(UI.java:410)
	at haven.UI.removeid(UI.java:418)
	at haven.UI.removeid(UI.java:418)
	at haven.UI.destroy(UI.java:672)
	at haven.HavenPanel.run(HavenPanel.java:849)
	at java.lang.Thread.run(Unknown Source)

**To Reproduce**
1. Run the client
2. Log in
3. Click the character button :)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Java Version: Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

**Comment by Cediner** [comment]
Update the client
Actual version is 2021.05.26
