### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by shampizle** [Cediner/ArdClient#52]
**Describe the bug**

**To Reproduce**
Run the Runme.bat file. and click on the character.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
2022.01.14.92ce471b
Windows 10 10.0 x64, 1.8.0_281 amd64
NVIDIA Corporation (NVIDIA GeForce RTX 3080/PCIe/SSE2) - 4.6.0 NVIDIA 497.09

java.lang.NoSuchMethodError: java.nio.ShortBuffer.rewind()Ljava/nio/ShortBuffer;
	at haven.FastMesh$VAOState.bindindbo(FastMesh.java:209)
	at haven.FastMesh$VAOState.apply(FastMesh.java:230)
	at haven.GLState$Applier.apply(GLState.java:571)
	at haven.FastMesh$VAOCompiler$VAOCompiled.draw(FastMesh.java:280)
	at haven.FastMesh.draw(FastMesh.java:387)
	at haven.RenderList.render(RenderList.java:448)
	at haven.RenderList.render(RenderList.java:520)
	at haven.PView.draw(PView.java:265)
	at haven.Avaview.draw(Avaview.java:290)
	at haven.Widget.draw(Widget.java:849)
	at haven.Widget.draw(Widget.java:865)
	at haven.Charlist.draw(Charlist.java:141)
	at haven.Widget.draw(Widget.java:849)
	at haven.Widget.draw(Widget.java:865)
	at haven.Widget.draw(Widget.java:849)
	at haven.Widget.draw(Widget.java:865)
	at haven.RootWidget.draw(RootWidget.java:82)
	at haven.UI.draw(UI.java:228)
	at haven.HavenPanel.rootdraw(HavenPanel.java:459)
	at haven.HavenPanel.run(HavenPanel.java:761)
	at java.lang.Thread.run(Unknown Source)

**Comment by Cediner** [comment]
fixed
