### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by erpione** [Cediner/ArdClient#53]
2022.01.14a.ba25695e
Windows 10 10.0 x64, 1.8.0_311 amd64
ATI Technologies Inc. (AMD Radeon(TM) Vega 6 Graphics) - 4.4.13596 Compatibility Profile Context 20.10.35.02 27.20.1034.6

java.lang.RuntimeException: Delayed error in resource gfx/terobjs/bushes/poppycaps (v13), from forking source backed by HTTP res source (https://game.havenandhearth.com/hres/)
	at haven.Resource$Pool$Queued.get(Resource.java:505)
	at haven.Resource$Pool$Queued.get(Resource.java:470)
	at haven.Session$CachedRes$Ref.get(Session.java:147)
	at haven.Session$CachedRes$Ref.get(Session.java:140)
	at haven.ResDrawable.getres(ResDrawable.java:173)
	at haven.Gob.getres(Gob.java:1640)
	at haven.Gob.res(Gob.java:1629)
	at haven.Gob.resname(Gob.java:1619)
	at haven.Gob.ctick(Gob.java:584)
	at haven.OCache.ctick(OCache.java:164)
	at haven.Glob.ctick(Glob.java:198)
	at haven.HavenPanel.run(HavenPanel.java:750)
	at java.lang.Thread.run(Unknown Source)
Caused by: haven.Resource$LoadException: Load error in resource gfx/terobjs/bushes/poppycaps(v13), from forking source backed by HTTP res source (https://game.havenandhearth.com/hres/)
	at haven.Resource$Pool.handle(Resource.java:564)
	at haven.Resource$Pool.access$1200(Resource.java:447)
	at haven.Resource$Pool$Loader.run(Resource.java:710)
	... 1 more
	Suppressed: haven.Resource$LoadException: Load error in resource gfx/terobjs/bushes/poppycaps(v13), from cache source backed by HashDirCache(https://game.havenandhearth.com/hres/)
		... 4 more
		Suppressed: haven.Resource$LoadException: Load error in resource gfx/terobjs/bushes/poppycaps(v13), from local res source (res-preload)
			... 4 more
			Suppressed: haven.Resource$LoadException: Load error in resource gfx/terobjs/bushes/poppycaps(v13), from local res source (res)
				... 4 more
			Caused by: java.io.FileNotFoundException: Could not find resource locally: /res/gfx/terobjs/bushes/poppycaps.res
				at haven.Resource$JarSource.get(Resource.java:355)
				at haven.Resource$Pool.handle(Resource.java:551)
				... 3 more
		Caused by: java.io.FileNotFoundException: Could not find resource locally: /res-preload/gfx/terobjs/bushes/poppycaps.res
			at haven.Resource$JarSource.get(Resource.java:355)
			at haven.Resource$Pool.handle(Resource.java:551)
			... 3 more
	Caused by: haven.Message$EOF: Required 16 bytes, got only 0
		at haven.Message.rensure(Message.java:114)
		at haven.Message.bytes(Message.java:197)
		at haven.Resource.load(Resource.java:1964)
		at haven.Resource.access$700(Resource.java:94)
		at haven.Resource$Pool.handle(Resource.java:554)
		... 3 more
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodError: java.nio.FloatBuffer.rewind()Ljava/nio/FloatBuffer;
	at haven.Utils.construct(Utils.java:2115)
	at haven.VertexBuf$1.cons(VertexBuf.java:633)
	at haven.VertexBuf$VertexRes.<init>(VertexBuf.java:674)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at haven.Resource$LayerConstructor.cons(Resource.java:940)
	at haven.Resource.load(Resource.java:1989)
	at haven.Resource.access$700(Resource.java:94)
	at haven.Resource$Pool.handle(Resource.java:554)
	... 3 more
Caused by: java.lang.NoSuchMethodError: java.nio.FloatBuffer.rewind()Ljava/nio/FloatBuffer;
	at haven.VertexBuf$FloatArray.<init>(VertexBuf.java:178)
	at haven.VertexBuf$TexelArray.<init>(VertexBuf.java:365)
	at haven.VertexBuf$TexelArray.<init>(VertexBuf.java:369)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at haven.Utils.construct(Utils.java:2107)
	... 13 more

**Comment by Cediner** [comment]
да ***** ****** ошибка
сейчас пересоберу
