### ISSUE TITLE
Map import error

### ISSUE THREAD

**Issue by OttoGrotto** [Cediner/ArdClient#78]
**Describe the bug**
Null error when trying to import a map

**To Reproduce**
1. Import a map
2. Wait for the data validation to complete
3. About 2% into the import you get the error

**Expected behavior**
The map to be imported

The error itself
```
[17:13] java.lang.NullPointerException
 
[17:13] 	at haven.MapFile$Importer.importgrid(MapFile.java:2405)
 
[17:13] 	at haven.MapFile$Importer.reimport(MapFile.java:2475)
 
[17:13] 	at haven.MapFile.reimport(MapFile.java:2499)
 
[17:13] 	at haven.MapFile.reimport(MapFile.java:2503)
 
[17:13] 	at haven.MapFileWidget.lambda$importmap$3(MapFileWidget.java:954)
 
[17:13] 	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Cediner** [comment]
Try click with CTRL on Import button and start it again

**Comment by OttoGrotto** [comment]
```
[17:17] java.lang.NullPointerException
 
[17:17] 	at haven.MapFile$Importer.importgrid(MapFile.java:2405)
 
[17:17] 	at haven.MapFile$Importer.reimport(MapFile.java:2475)
 
[17:17] 	at haven.MapFile.reimport(MapFile.java:2499)
 
[17:17] 	at haven.MapFile.reimport(MapFile.java:2503)
 
[17:17] 	at haven.MapFileWidget.lambda$importmap$3(MapFileWidget.java:954)
 
[17:17] 	at java.base/java.lang.Thread.run(Thread.java:833)
```
Got this
