### ISSUE TITLE
NullPointerException after character selection / world loading

### ISSUE THREAD

**Issue by Isabur** [Cediner/ArdClient#79]
**Describe the bug**

**NullPointerException after character selection / world loading**

**To Reproduce**

**1. Start client
2. Login
3. Select character
4. waiting until world loaded
5. open debug channel
6. read exceptions**

**Expected behavior**

**No exceptions after world loaded**

**Screenshots**

**Desktop (please complete the following information):**
 **- OS: Windows 11
 - OpenJDK**

**Additional context**

**[12:47] java.lang.NullPointerException: Cannot invoke "java.awt.Color.getRed()" because "c" is null
[12:47] 	at haven.Utils.c2fa(Utils.java:1877)
[12:47] 	at haven.States$ColState.<init>(States.java:50)
[12:47] 	at haven.GOut.chcolor(GOut.java:788)
[12:47] 	at haven.CharWnd$GlutMeter.draw(CharWnd.java:295)
[12:47] 	at haven.Widget.draw(Widget.java:874)
[12:47] 	at haven.Widget.draw(Widget.java:906)
[12:47] 	at haven.Widget.draw(Widget.java:874)
[12:47] 	at haven.Widget.draw(Widget.java:906)
[12:47] 	at haven.Widget.draw(Widget.java:874)
[12:47] 	at haven.Widget.draw(Widget.java:906)
[12:47] 	at haven.sloth.gui.MovableWidget.draw(MovableWidget.java:216)
[12:47] 	at haven.Window.draw(Window.java:690)
[12:47] 	at haven.Widget.draw(Widget.java:874)
[12:47] 	at haven.Widget.draw(Widget.java:906)
[12:47] 	at haven.GameUI.draw(GameUI.java:1366)
[12:47] 	at haven.Widget.draw(Widget.java:874)
[12:47] 	at haven.Widget.draw(Widget.java:906)
[12:47] 	at haven.RootWidget.draw(RootWidget.java:90)
[12:47] 	at haven.UI.draw(UI.java:241)
[12:47] 	at haven.HavenPanel.rootdraw(HavenPanel.java:463)
[12:47] 	at haven.HavenPanel.run(HavenPanel.java:771)
[12:47] 	at java.base/java.lang.Thread.run(Thread.java:1589)**

**Comment by Isabur** [comment]
I restart the client 5 times and now the client works normallly
