### ISSUE TITLE
java.lang.RuntimeException: Pagina in <q:paginae/act/landscape(v5)> lacks action

### ISSUE THREAD

**Issue by Isabur** [Cediner/ArdClient#80]
**Describe the bug**

**After world is loaded the MenuGrid is not created as normal and the exception is thrown.
The exception is repeated every few seconds in a loop.**

**To Reproduce**
**1. Start client
2. Login
3. Choose character
4. Waiting for word loading
5. Exception will be thrown during MenuGrid creation

This behavior is not every time, this happens sometimes! It feels like a timing/thread thing.**

**Expected behavior**

After world is loaded the MenuGrid should be created in the indeeded fashion and no exception should be thrown.

**Screenshots**

![image](https://user-images.githubusercontent.com/95970943/226375472-9a667c54-b94d-4d53-b534-25599e9f6c15.png)

![image](https://user-images.githubusercontent.com/95970943/226375732-3d738bc1-87d7-4a23-87af-db89116e01ca.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - OpenJDK

**Additional context**

**15:38] java.lang.RuntimeException: Pagina in <q:paginae/act/landscape(v5)> lacks action
[15:38] 	at haven.MenuGrid.cons(MenuGrid.java:480)
[15:38] 	at haven.MenuGrid.updlayout(MenuGrid.java:1263)
[15:38] 	at haven.MenuGrid.tick(MenuGrid.java:1517)
[15:38] 	at haven.Widget.tick(Widget.java:833)
[15:38] 	at haven.Widget.tick(Widget.java:833)
[15:38] 	at haven.GameUI.tick(GameUI.java:1430)
[15:38] 	at haven.Widget.tick(Widget.java:833)
[15:38] 	at haven.RootWidget.tick(RootWidget.java:98)
[15:38] 	at haven.UI.tick(UI.java:235)
[15:38] 	at haven.HavenPanel.run(HavenPanel.java:762)
[15:38] 	at java.base/java.lang.Thread.run(Thread.java:1589)**

**Comment by Isabur** [comment]
When I try to ignore the error and want to craft a feather trinket the error will be thrown with a error window and the client crashs.
![image](https://user-images.githubusercontent.com/95970943/226810745-dff5f7fb-e714-405b-a119-bfed38b626d1.png)

**Comment by Isabur** [comment]
I restart the client 5 times, now the client works normally as it should

**Comment by Cediner** [comment]
Try change a cache storage with General - SQLite (first line).
Previously do a map export.

**Comment by Isabur** [comment]
Thank you very much for your great work here.

Your advice works for me.
I have tested it multiple times at morning without errors.
