### ISSUE TITLE
Newest Version Broken

### ISSUE THREAD

**Issue by Leviwulfish** [Cediner/ArdClient#83]
Newest version throwing 
java.lang.NoSuchMethodError: com.jogamp.common.util.SecurityUtil.doPrivileged(Ljava/security/PrivilegedAction;)Ljava/lang/Object;

**To Reproduce**
1. Launch run_console.bat

**Expected behavior**
Files run, game launches

**Screenshots**

**Desktop (please complete the following information):**
 Windows 10
 Java 1.8.0_144

**Comment by Leviwulfish** [comment]
Full error log because I'm going to bed and I don't want to leave you without a followup if you hop in
2023.10.22.ae1d3215
Windows 10 10.0 x64, 1.8.0_144 amd64
null

java.lang.NoSuchMethodError: com.jogamp.common.util.SecurityUtil.doPrivileged(Ljava/security/PrivilegedAction;)Ljava/lang/Object;
	at jogamp.opengl.Debug.<clinit>(Debug.java:44)
	at com.jogamp.opengl.awt.GLCanvas.<clinit>(GLCanvas.java:170)
	at haven.States.<clinit>(States.java:42)
	at haven.glsl.BaseColor.<clinit>(BaseColor.java:37)
	at haven.States$ColState.<clinit>(States.java:101)
	at haven.sloth.gob.Movable.<clinit>(Movable.java:39)
	at haven.DefSettings.init(DefSettings.java:397)
	at haven.MainFrame.main2(MainFrame.java:450)
	at haven.MainFrame.lambda$main$1(MainFrame.java:493)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Lukash4k1** [comment]
same using java 17.0.7

**Comment by Cediner** [comment]
reverted
check update
