### ISSUE TITLE
[LINUX]error at run.sh start 

### ISSUE THREAD

**Issue by Fr-Dae** [Cediner/ArdClient#88]
**Desktop** dae@dae-GL753VD (ROG)
**OS**: Ubuntu 22.04.3 LTS x86_64 
**Host**: GL552VW 1.0 
**Kernel**: 5.15.0-88-generic 
Resolution: 1920x1080, 1050x1680 
**DE**: LXDE 
WM: Openbox 

**CPU**: Intel i7-6700HQ (8) @ 3.500GHz 
**GPU**: Intel HD Graphics 530 
**GPU**: NVIDIA GeForce GTX 960M 
**Memory**: 7272MiB / 15412MiB 

**Describe the bug**
dae@dae-GL753VD:~/Games/Haven/LauncherUnstable-ard/CustomClientUnstable$ bash ./run.sh 

Error: Unable to access jarfile build/hafen.jar
./run_Java16+.sh: ligne 4: $'pause\r' : commande introuvable

**Comment by MvGulik** [comment]
More or less the same.
run_Java16+.sh => bad interpreter: No such file or directory
Linux Mint (although it seem more a Github issue)

**Comment by Cediner** [comment]
I don't have Linux. This sh code runs fine for me.

**Comment by MvGulik** [comment]
?
Is the *.sh script not specific/only for linux install of client ?

**Comment by Cediner** [comment]
I do not understand your question. Using simulation programs, I ran this script on windows.
the command to run the client is very simple: **java -jar build/hafen.jar** in the main folder

**Comment by Kenshut-not-dead** [comment]
You can run the client on linux by changing the file.
just delete everything that comes after the 3rd line

**Comment by Fr-Dae** [comment]
first i have make all the folder executable with `sudo chmod -R 775 ./`
then, i have start the script with 

```
bash ./run_Java16+.sh
[LOG] Downloading new version file
[LOG] Comparing version files
[LOG] No update required
[LOG] Moving over new version file
[LOG] Starting client
Error: Unable to access jarfile build/hafen.jar
./run_Java16+.sh: ligne 4: $'pause\r' : command not found
```
THEN, make the folder, executable (again) `sudo chmod -R 775 ./`
i start manually the build with
`java -jar ./build/hafen.jar `
```js
2023.12.16.84642256
Linux 5.15.0-89-generic, 21-ea amd64
Intel (Mesa Intel(R) HD Graphics 530 (SKL GT2)) - 4.6 (Core Profile) Mesa 23.3~git2310160600.ccdea7~oibaf~j (git-ccdea7b 2023-10-16 jammy-oibaf-ppa)

java.lang.RuntimeException: javax.media.opengl.GLException: Not a GL2 implementation
	at com.jogamp.common.util.awt.AWTEDTExecutor.invoke(AWTEDTExecutor.java:58)
	at jogamp.opengl.awt.AWTThreadingPlugin.invokeOnOpenGLThread(AWTThreadingPlugin.java:103)
	at jogamp.opengl.ThreadingImpl.invokeOnOpenGLThread(ThreadingImpl.java:206)
	at javax.media.opengl.Threading.invokeOnOpenGLThread(Threading.java:172)
	at javax.media.opengl.Threading.invoke(Threading.java:191)
	at javax.media.opengl.awt.GLCanvas.display(GLCanvas.java:528)
	at haven.HavenPanel$6.uglyjoglhack(HavenPanel.java:683)
	at haven.HavenPanel$6.run(HavenPanel.java:695)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: javax.media.opengl.GLException: Not a GL2 implementation
	at jogamp.opengl.gl4.GL4bcImpl.getGL2(GL4bcImpl.java:37164)
	at haven.HavenPanel$1.display(HavenPanel.java:154)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:649)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:633)
	at javax.media.opengl.awt.GLCanvas$9.run(GLCanvas.java:1271)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1103)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:978)
	at javax.media.opengl.awt.GLCanvas$10.run(GLCanvas.java:1282)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```
Finally, I downloaded 50 Mio of  non-essential, non-dmca-free data for nothing. 


by the way, 
I still haven't authorised you to publish my code work (which was done with deepl and not google, plus a manual proofreading), 
or else credit me and the other contributor instead of attributing other people's work to you.

**Comment by Fr-Dae** [comment]
in addition
, most versions of debian/ubuntu have opej-jdk 19, we are currently on version 21.
https://jdk.java.net/21/
https://launchpad.net/%7Eopenjdk-r/+archive/ubuntu/ppa

**Comment by Cediner** [comment]
Well. There are no plans to touch this yet. don't use linux. or solve this problem yourself.
p.s. I deleted your shitl translation and made my own translation using google. mind your head, not sabotage.

**Comment by MvGulik** [comment]
Closed ... Bummer ... O well.

Anyway ... I solved part one. (_which had nothing to do with "pause" btw. It had to do with what generally comes directly after it, or before it_.)

Now it just seems I have the wrong Java flavor. Darn.
```
"2023.12.16.84642256
Linux 5.4.0-169-generic, 17.0.6 amd64
null

java.lang.UnsatisfiedLinkError: /tmp/jogamp_0000/file_cache/jln8859392530293360273/jln3759150561610673479/libnativewindow_awt.so: /usr/lib/jvm/java-17-oracle/lib/libjawt.so: version `SUNWprivate_1.1' not found (required by /tmp/jogamp_0000/file_cache/jln8859392530293360273/jln3759150561610673479/libnativewindow_awt.so)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	...
```
