### ISSUE TITLE
Unable to see upstairs in buildings

### ISSUE THREAD

**Issue by cmoondev** [Cediner/ArdClient#95]
**Describe the bug**
Unable to see upstairs gob in buildings. Verified from multiple different computers.
* Res: gfx/terobjs/arch/upstairs
* Ver: 25

**To Reproduce**
1. Go to inside any building with an upstairs

**Stack Trace**
```java
haven.Resource$LoadException: Load error in resource gfx/terobjs/arch/upstairs(v25), from cache source backed by modification.SQLiteCache@20fc77d8
        at haven.Resource$CodeEntry.getentry(Resource.java:2061)
        at haven.Resource$CodeEntry.get(Resource.java:2091)
        at haven.Resource.getcode(Resource.java:1917)
        at haven.Sprite.create(Sprite.java:188)
        at haven.ResDrawable.init(ResDrawable.java:126)
        at haven.ResDrawable.waitforinit(ResDrawable.java:53)
        at haven.ResDrawable.ctick(ResDrawable.java:160)
        at haven.Gob.ctick(Gob.java:977)
        at haven.OCache.lambda$ctick$1(OCache.java:218)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1051)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1069)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
Caused by: java.lang.ClassNotFoundException: haven.ModSprite
        at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at haven.Resource$CodeEntry.getentry(Resource.java:2059)
        ... 18 more
```

**Additional Notes**
Stairs are still interactable using the Traverse hotkey (SHIFT+A by default)

**Comment by Cediner** [comment]
invisible update of resources by developers
fixed https://github.com/Cediner/ArdClient/commit/8beb4b5e919ad8cf6c4b35a14788d00efdcdd376

**Comment by cmoondev** [comment]
Thanks for the quick update. I can see the stairs now but it looks like a texture is missing. Is there any fix for that?
![upstairs_missing_texture](https://github.com/user-attachments/assets/fac44e58-2694-4638-ab1f-6a9179488b74)

**Comment by Cediner** [comment]
https://github.com/Cediner/ArdClient/commit/9c07d44f6d5c725daed927f4714d7cca91da3911

**Comment by cmoondev** [comment]
All looks good, thanks!
